config/routes.rb
Rails.application.routes.draw do
  root "students#index"
  resources :students

  resources :subjects

  resources :marks

end

app/models/mark.rb
class Mark < ActiveRecord::Base
	belongs_to :student
	belongs_to :subject
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :marks
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :marks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController

	def index
		@students = Student.all
		@subjects = Subject.all
		@marks = Mark.all
	end

	def new
		#@student = Student.find(params[:student_id])
		#@marks = @student.marks.build
		@subject_options = Subject.all.map{|t| [ t.subject, t.id ] }
		@student_options = Student.all.map{|u| [ u.name, u.id ] }
		@mark = Mark.new
	end

	def create
		#@mark = @student.marks.create(mark_params)
		@mark = Mark.create(mark_params)
		if @mark.errors.empty?
			redirect_to @mark
		else
			render 'new'
		end
	end

	def show
		@mark = Mark.find(params[:id])
		@marks = Mark.all
	end


	def edit
		@mark = Mark.find_by_id(params[:id])
		@subject_options = Subject.all.map{|t| [ t.subject, t.id ] }
		@student_options = Student.all.map{|u| [ u.name, u.id ] }
	end

	def update
		@mark = Mark.find_by_id(params[:id])
		@mark.update_attributes(mark_params)
		if @mark.errors.empty?
			redirect_to @mark
		else
			render 'edit'
		end
	end

	def destroy
		@mark = Mark.find_by_id(params[:id])
		@mark.destroy
		redirect_to marks_path
	end

	private
		def mark_params
			params.require(:mark).permit(:student_id, :subject_id, :mark, :semestr)
		end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.all
		@subjects = Subject.all
		@marks = Mark.all
	end

	def new
  		@student = Student.new
			@marks = Mark.new
			@subjects = Subject.all
	end

	def create
		@student = Student.create(students_params)
		if @student.errors.empty?
			redirect_to @student
		else
			render 'new'
		end
	end

	def show
		@student = Student.find(params[:id])
		@subject = Subject.all
		#@subject.each do
				#subjectId = subject.id
				#@mark = Mark.find_by_student_id_and_subject_id(params[:id, :subjectId])
		#end

		@marks = Mark.all
		@mark = Mark.find_by_student_id(params[:id])
	end

	def edit
		@student = Student.find_by_id(params[:id])
	end

	def update
		@student = Student.find_by_id(params[:id])
		@student.update_attributes(students_params)
		if @student.errors.empty?
			redirect_to @student
		else
			render 'edit'
		end
	end

	def destroy
		@student = Student.find_by_id(params[:id])
		@student.destroy
		redirect_to students_path
	end

	private
		def students_params
			params.require(:student).permit(:surname, :name, :email, :group, :birth, :opinion)
		end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	def show
		@subject = Subject.find(params[:id])
	end

	def index
		@subjects = Subject.all
	end

	def new
		@subject = Subject.new
	end

	def create
		@subject = Subject.create(subject_params)
		if @subject.errors.empty?
			redirect_to @subject
		else
			render 'new'
		end
	end

	def edit
		@subject = Subject.find_by_id(params[:id])
	end

	def update
		@subject = Subject.find_by_id(params[:id])
		@subject.update_attributes(subject_params)
		if @subject.errors.empty?
			redirect_to @subject
		else
			render 'edit'
		end
	end

	def destroy
		@subject = Subject.find_by_id(params[:id])
		@subject.destroy
		redirect_to subjects_path
	end

	private
		def subject_params
			params.require(:subject).permit(:subject)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/marks/edit.html.erb
<h1>Редактирвоать оценку:</h1>
<%= form_for @mark do |f| %>
	<table>
		<tr>
			<td>
  				<b>Student ID: </b>
			</td>
			<td>
				<%#= f.text_field :student_id %>

          <%#= f.text_field :student_id, collection: @students, as: :grouped_select, group_method: :name %>

          <%#= select_tag(:student_id, options_for_select(@student_options)) %>
          <%= f.select(:student_id, @student_options) %>
			</td>
		</tr>
		<tr>
			<td>
  				<b>Subject ID: </b>
  			</td>
  			<td>
  				<%= f.select(:subject_id, @subject_options) %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Mark: </b>
  			</td>
  			<td>
  				<%= f.text_field :mark %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Semestr: </b>
  			</td>
  			<td>
  				<%= f.text_field :semestr %>
  			</td>
  		</tr>
	</table>
  <%= f.submit "Create Mark" %>
<% end %>

app/views/marks/index.html.erb
<table border="1px" border-color="#000">
	<tr>
		<td>
			id
		</td>
		<td>
			Student ID
		</td>
		<td>
			Subject ID
		</td>
		<td>
			Mark
		</td>
		<td>
			Semestr
		</td>
    <td>
			Action
		</td>
	</tr>
	<% @marks.each do |mark| %>
		<tr>
      <td>
				<%= mark.id %>
			</td>
			<td>
				<%= mark.student_id %>
			</td>
			<td>
				<%= mark.subject_id %>
			</td>
			<td>
				<%= mark.mark %>
			</td>
			<td>
				<%= mark.semestr %>
			</td>
      <td>
        <%= link_to 'Редактировать', edit_mark_path(mark.id) %>
				<%= link_to 'Удалить', mark, method: :delete %>
			</td>
		</tr>
	<% end %>
</table>
<button><%= link_to 'Добавить оценку', new_mark_path %></button>

app/views/marks/new.html.erb
<h1>Добавить оценку:</h1>
<%= form_for @mark do |f| %>
	<table>
		<tr>
			<td>
  				<b>Student ID: </b>
			</td>
			<td>
				<%#= f.text_field :student_id %>

          <%#= f.text_field :student_id, collection: @students, as: :grouped_select, group_method: :name %>

          <%#= select_tag(:student_id, options_for_select(@student_options)) %>
          <%= f.select(:student_id, @student_options) %>
			</td>
		</tr>
		<tr>
			<td>
  				<b>Subject ID: </b>
  			</td>
  			<td>
  				<%= f.select(:subject_id, @subject_options) %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Mark: </b>
  			</td>
  			<td>
  				<%= f.text_field :mark %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Semestr: </b>
  			</td>
  			<td>
  				<%= f.text_field :semestr %>
  			</td>
  		</tr>
	</table>
  <%= f.submit "Create Mark" %>
<% end %>

app/views/marks/show.html.erb
<h1>Добавленная оценка: </h1>
<p>id: <%= @mark.id %> </p>
<p>Студент: <%= @mark.student_id %> </p>
<p>Предмет: <%= @mark.subject_id %> </p>
<p>Оценка: <%= @mark.mark %> </p>
<p>Семестр: <%= @mark.semestr %> </p>

app/views/students/edit.html.erb
<h1>Редактировать студента:</h1>
<%= form_for @student do |f| %>
	<table>
		<tr>
			<td>
  				<b>ID: </b>
			</td>
			<td>
				<%= f.text_field :id %>
			</td>
		</tr>
		<tr>
			<td>
  				<b>Surname: </b>
			</td>
			<td>
				<%= f.text_field :surname %>
			</td>
		</tr>
		<tr>
			<td>
  				<b>Name: </b>
  			</td>
  			<td>
  				<%= f.text_field :name %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Email: </b>
  			</td>
  			<td>
  				<%= f.text_field :email %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Group: </b>
  			</td>
  			<td>
  				<%= f.text_field :group %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Birth: </b>
  			</td>
  			<td>
  				<%= f.text_field :birth %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Opinion: </b>
  			</td>
  			<td>
  				<%= f.text_field :opinion %>
  			</td>
  		</tr>
	</table>
	<%= f.submit "Edit Student" %>
<% end %>

app/views/students/index.html.erb
<table border="1px" border-color="#000">
	<tr>
		<td>
			id
		</td>
		<td>
			Фамилия
		</td>
		<td>
			Имя
		</td>
		<td>
			Почта
		</td>
		<td>
			Группа
		</td>
		<td>
			Дата рождения
		</td>
		<td>
			Характеристика научного руководителя
		</td>
		<td>
			Действие
		</td>
	</tr>
	<% @students.each do |student| %>
		<tr>
			<td>
				<%= student.id %>
			</td>
			<td>
				<%= student.surname %>
			</td>
			<td>
				<%= student.name %>
			</td>
			<td>
				<%= student.email %>
			</td>
			<td>
				<%= student.group %>
			</td>
			<td>
				<%= student.birth %>
			</td>
			<td>
				<%= student.opinion %>
			</td>
			<td>
				<%= link_to 'Просмотреть', student_path(student.id) %>
				<%= link_to 'Редактировать', edit_student_path(student.id) %>
				<%= link_to 'Удалить', student, method: :delete %>
			</td>
		</tr>
	<% end %>
</table>

<br />

<button><%= link_to 'Добавить нового студента', new_student_path %></button>

<br />
<br />



<table border="1px">
	<tr>
		<td>id-subject</td>
		<td>Предмет</td>
	</tr>
	<% @subjects.each do |subject| %>
		<tr>
			<td><%= subject.id %></td>
			<td><%= subject.subject %></td>
		</tr>
	<% end %>
</table>


<br />


<table border="1px" border-color="#000">
	<tr>
		<td>
			id
		</td>
		<td>
			Student ID
		</td>
		<td>
			Subject ID
		</td>
		<td>
			Mark
		</td>
		<td>
			Semestr
		</td>
    <td>
			Action
		</td>
	</tr>
	<% @marks.each do |mark| %>
		<tr>
      <td>
				<%= mark.id %>
			</td>
			<td>
				<%= mark.student_id %>
			</td>
			<td>
				<%= mark.subject_id %>
			</td>
			<td>
				<%= mark.mark %>
			</td>
			<td>
				<%= mark.semestr %>
			</td>
      <td>
        <%= link_to 'Редактировать', edit_mark_path(mark.id) %>
				<%= link_to 'Удалить', mark, method: :delete %>
			</td>
		</tr>
	<% end %>
</table>

<%#= @students.inspect %>

app/views/students/new.html.erb
<h1>Добавить студента:</h1>
<%= form_for @student do |f| %>
	<table>
		<tr>
			<td>
  				<b>Surname: </b>
			</td>
			<td>
				<%= f.text_field :surname %>
			</td>
		</tr>
		<tr>
			<td>
  				<b>Name: </b>
  			</td>
  			<td>
  				<%= f.text_field :name %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Email: </b>
  			</td>
  			<td>
  				<%= f.text_field :email %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Group: </b>
  			</td>
  			<td>
  				<%= f.text_field :group %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Birth: </b>
  			</td>
  			<td>
  				<%= f.text_field :birth %>
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<b>Opinion: </b>
  			</td>
  			<td>
  				<%= f.text_field :opinion %>
  			</td>
  		</tr>
	</table>
  <%= f.submit "Create Student" %>
<% end %>

app/views/students/show.html.erb
<h1>Добавленный студент: </h1>
<p>id: <%= @student.id %> </p>
<p>Фамилия: <%= @student.surname %> </p>
<p>Имя: <%= @student.name %> </p>
<p>E-mail: <%= @student.email %> </p>
<p>Дата рождения: <%= @student.birth %> </p>
<p>Группа: <%= @student.group %> </p>
<p> Средний балл: <%= @student.average_mark %> </p>
<p>Мнение научного руководителя:  <%= @student.opinion %> </p>
<br />
<h2>Оценки по предметам</h2>
<table>
	<tr>
		<td>id-subject</td>
		<td>Предмет</td>
    <td>Оценка</td>
	</tr>
	
</table>
<button><%= link_to 'Редактировать данные студента', edit_student_path(@student.id) %></button>
<button><%= link_to 'Добавить нового студента', new_student_path %></button>

app/views/subjects/edit.html.erb
<h1>Редактировать предмет:</h1>
<%= form_for @subject do |f| %>
	<table>
		<tr>
			<td>
  				<b>ID: </b>
			</td>
			<td>
				<%= f.text_field :id %>
			</td>
		</tr>
		<tr>
			<td>
  				<b>Subject Name: </b>
			</td>
			<td>
				<%= f.text_field :subject %>
			</td>
		</tr>
	</table>
	<%= f.submit "Edit Subject" %>
<% end %>

app/views/subjects/index.html.erb
<table border="1px">
	<tr>
		<td>id-subject</td>
		<td>Предмет</td>
		<td>Действие</td>
	</tr>
	<% @subjects.each do |subject| %>
		<tr>
			<td><%= subject.id %></td>
			<td><%= subject.subject %></td>
			<td>
				<%= link_to 'Редактировать', edit_subject_path(subject.id) %>
				<%= link_to 'Удалить', subject, method: :delete %>
			</td>
		</tr>
	<% end %>
</table>

<button><%= link_to 'Добавить новый предмет', new_subject_path %></button>

<%#= @students.inspect %>

app/views/subjects/new.html.erb
<h1>Добавить предмет:</h1>
<%= form_for @subject do |f| %>
	<table>
		<tr>
			<td>
  				<b>Subject Name: </b>
			</td>
			<td>
				<%= f.text_field :subject %>
			</td>
		</tr>

	</table>
  <%= f.submit "Create Subject" %>
<% end %>

app/views/subjects/show.html.erb
<h1>Добавленный предмет: </h1>
<p>id: <%= @subject.id %> </p>
<p>Предмет: <%= @subject.subject %> </p>
<br />
<button><%= link_to 'Редактировать данные предмета', edit_subject_path(@subject.id) %></button>
<button><%= link_to 'Добавить новый предмет', new_subject_path %></button>